### PR TITLE
Delay scheduled update reboot

### PR DESCRIPTION
**Pull request by bharrisau**
Ensures all devices are finished updating before any start rebooting.

### CODE REVIEW

**Comment by eworm-de** [comment]
This makes just little to no sense to me... First part of your code is dead and will never be reached, second part adds a delay on **non**-scheduled update.

So what are your trying to achieve here? Note this is about downloading packages to the local device and rebooting - what "*all devices*" are you referencing here?

**Comment by bharrisau** [comment]
I'm pretty sure the logic I've got there is:
- if interactive and schedule reboot - set a schedule time at 3am
- if interactive and immediate reboot, reboot now
- if non-interactive then reboot after 5 minutes


I have a bunch of systems that run the update at the same scheduled time, so they all download and install. And then reboot 5 minutes later.

**Comment by eworm-de** [comment]
Ah, my fault... I should not review pull requests on a smartphone display. 😝

Still the title is wrong, or at least very misleading. The script itself supports a scheduled reboot - that made me think you are changing that code path. Something like "_delay non-interactive update reboot_" fits better I think.

Anyway, I am not really happy with this, as it would annoy me. For example I run `packages-update` from `telegram-chat`, and an additional delay of five minutes would make things a lot worse for me.

Perhaps this should stay as-is, but there is a simple solution for you: `packages-update` supports running backup scripts, and you can hook in there. Just add a new script, with this content:

```
# provides: backup-script, order=99
:delay 5m;
```

(This requires a change from `next` branch, I am just about to add the functionality of ordering backup scripts.)

Add the magic first line ("`#!rsc by RouterOS`") and place it on a web server to install it as [custom script](https://git.eworm.de/cgit/routeros-scripts/about/#installing-custom-scripts-modules). Is that something that works for you? Any thoughts?

**Comment by eworm-de** [comment]
Testing with update to RouterOS `7.12beta7` and merged into `main`.

**Pull request closed without merging**
