### PR TITLE
Allow sms forward actions

### PR DESCRIPTION
**Pull request by bubenkoff**

### CODE REVIEW

**Comment by eworm-de** [comment]
Are you aware that the script [sms-action](https://github.com/eworm-de/routeros-scripts/blob/main/doc/sms-action.md) exists? Why reinvent and duplicate code for `sms-forward`?

**Comment by bubenkoff** [comment]
@eworm-de thank you for mentioning it, yes I do, but it's not the same thing
sms-actions relies on the built-in sms-in message format
This approach allows parsing arbitrary SMS and acting based on those
the use case I use it for currently is to order the traffic bundles automatically when the warning SMS about 80% usage is received. It then sends an SMS to the provider to order a new package.

**Comment by eworm-de** [comment]
Ah, got the idea. 😜
I will have another look with some spare time.

**Comment by eworm-de** [comment]
I am very unhappy with the naming. As mentioned we have [sms-action](https://github.com/eworm-de/routeros-scripts/blob/main/doc/sms-action.md). That does something different, in facts acting on the received sms. The primary use of `sms-forward` is to forward sms messages, with the new functionality hooking in. So this is my proposal: Let's put "_Hook_" in naming.

Also I do not like to recycle the `allowed-number` property here. Let's keep that for `sms-action`. I would prefer to have an allowed number for each hook, preferable as regular expression so matching several numbers is possible.

So I think something like this could serve the configuration:
```
:local SmsForwardHooks {
  { match="magic string";
    allowed-number="1234";
    command="/system/script/run ..." };
# add more here...
};
```

Do you think that's reasonable?

**Comment by bubenkoff** [comment]
good points, will update the PR

**Comment by bubenkoff** [comment]
@eworm-de your points are now implemented, please re-review
BTW: can you please use the standard github code review tools to comment on the code?

**Comment by eworm-de** [comment]
Merged in ea09a18d3f05b20ff7f1ec25aea74f32d68ca5e0, with some modifications. Thanks!

**Pull request closed without merging**
