### PR TITLE
dhcp-to-dns: add support for pool name in fqdn

### PR DESCRIPTION
**Pull request by netztrip**
This adds support for pool names in the fqdn. I use it for a simple DMZ setup in my home network and would love to see it upstreamed. It works as expected for me but to be honest I understand only half the code.

### CODE REVIEW

**Comment by eworm-de** [comment]
Sounds reasonable, no idea why I did not come up with this myself. Did not yet look at the code, though - will try to find some spare time in the coming days.

Possibly the code could even drop support for the prefix. Having a pool with that name would have the same effect.

**Comment by eworm-de** [comment]
Not just the pool has a name, but the dhcp server itself (see column `name` in `/ip dhcp-server`). Would you be fine with that as well? I prepared my proposed changes in 4ba4edd7fe3e458787609dfb8785bce5ed0cf174.

**Comment by netztrip** [comment]
Sure, less work same outcome - I like it. Thanks for your efforts.

**Comment by eworm-de** [comment]
Closed via 2e1acc25059b9cc671a96ad648ef854a5bb29202.

**Pull request closed without merging**
